version: '3'

services:
  node-server:
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ./node:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - python-server

  python-server:
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./python:/app
    ports:
      - "5000:5000"
    
